common:
  root_child: main
  parameters:
    online: 1

variables:
  input: ["a","b","c","d","e","f","g","h","i","k"]

nodes:
  global:
    main:
      type: parallel
      children: [error_handler, main_sequence]

    error_handler:
      type: parallel
      children: [start_flight_error]

    start_flight_error:
      type: sequence
      children: [start_flight_error_if, start_flight_error_action, start_flight_error_sleep]

    start_flight_error_if:
      type: condition
      S: error_code = START_FLIGHT_ERROR
      R: default

    start_flight_error_action:
      type: action
      assign:
        cmd_emergency_land: 1

    start_flight_error_sleep:
      type: condition
      R: default


    main_sequence:
      type: sequence
      children: [on_start_tree, tree_body]

    on_start_tree:
      type: condition
      S: start_tree = 1
      F: start_tree < 0
      R: default

    tree_body:
      type: skipper
      children: [on_enter_tree, tree_exec]

    on_enter_tree:
      type: skipper
      children: [on_skip, on_go]

    on_skip:
      type: sequence
      children: [on_skip_if, on_skip_act]

    on_skip_if:
      type: condition
      S: SIG_skip = 1
      R: default

    on_skip_act:
      type: action
      assign:
        skip: 1

    on_go:
      type: sequence
      children: [on_go_if, on_go_act]

    on_go_if:
      type: condition
      S: SIG_go = 1
      R: default

    on_go_act:
      type: action
      assign:
        go: 1

    tree_exec:
      type: sequence
      children: [send_start, correctly_started]

    send_start:
      type: selector
      children: [if_send_start_done, send_start_action]

    if_send_start_done:
      type: condition
      S: cmd_flight_start = 1
      F: default

    send_start_action:
      type: action
      assign:
        cmd_flight_start: 1
        cmd_flight_start_response: 0

    correctly_started:
      type: selector
      children: [correctly_started_if, correctly_started_error_action]

    correctly_started_if:
      type: condition
      S: cmd_flight_start_response > 0
      F: cmd_flight_start_response < 0
      R: default

    correctly_started_error_action:
      type: action
      assign:
        error_code: START_FLIGHT_ERROR


